### ISSUE TITLE
How do I test the SOM network?

### ISSUE THREAD

**Issue by osteinjr** [spiglerg/Kohonen_SOM_Tensorflow#1]
Hello Spiglerg, I'm a bit confused as to the network test, could you help me understand using the tensorflow?
For example suppose I have a color set to RGB [0.25 0.25 0.25], how would I know which neuron was excited? What color does it represent? And how do you know if the color is correct or not?

Grateful!

**Comment by spiglerg** [comment]
No worries. :)

Colors are represented as input vectors with three components (RGB), each one in [0, 1]. For example, (1, 0, 0) is Red, (0, 1, 0) Green, (1, 1, 1) White, and (0.25, 0.25, 0.25) is a dark gray (RGB=[64, 64, 64]).

Kohonen Self-Organising Maps learn a mapping from the space of the input vectors to a 2D space (the network layer). The test example uses a presents a set of color vectors to the network as inputs, in order to have it learn a 2D representation of the RGB space of colors.
When an input vector is shown to the network, the unit whose weights most closely match it (by euclidean distance) is selected as the winner, and the "activation" of its neighbors is set to a gaussian profile. You can use my implementation to compute the index of the winning note with
    s.get_batch_winner(batch_of_inputs)

I didn't really understand what you meant by your last question, but the color-coded image that is shown reports the color preference of each unit in the network, that is the weights of the network.
